name: Flask App CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r flask_admin_app/requirements.txt

      - name: Initialize test database
        run: |
          python -c "from flask_admin_app.app import app, db; app.app_context().push(); db.create_all()"

      - name: Run unit tests
        run: |
          python -m unittest discover flask_admin_app
