import unittest
from models import User

class TestUserModel(unittest.TestCase):
    def test_user_repr(self):
        user = User(username='admin')
        self.assertEqual(repr(user), '<User admin>')

class TestMath(unittest.TestCase):
    def test_math(self):
        self.assertEqual(2 + 2, 4)

if __name__ == '__main__':
    unittest.main()
